services:
  runner:
    build:
      context: .
    container_name: ${RUNNER_NAME}
    image: github-runner:latest
    restart: always
    environment:
      - PERSONAL_REPOSITORY=${GIT_REPO}
      - PERSONAL_TOKEN=${GIT_TOKEN}
      - RUNNER_NAME=${RUNNER_NAME}
      - SQLSERVER_USER=${SQLSERVER_USER}
      - SQLSERVER_PWD=${SQLSERVER_PWD}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.35"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 252M
    network_mode: "host"
