services:
  runner:
    container_name: runner
    image: local/github-runner:latest
    restart: always
    environment:
      - PERSONAL_REPOSITORY=user/repo
      - PERSONAL_TOKEN=TOKEN
      - RUNNER_NAME=example-name
      - SQLSERVER_USER=${SQLSERVER_USER}
      - SQLSERVER_PWD=${SQLSERVER_PWD}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.35"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 252M
    network_mode: "host"
